version: '3.8'

services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        networks:
            - lnmp-network
        volumes:
            - ./nginx/log:/var/log/nginx
            - ../projects/project1:/var/www/:z
            - ./docker/nginx/config/conf.d:/etc/nginx/conf.d:z
            - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:z

    php:
        build:
            # args:
            #     user: web
            #     uid: 1001
            context: ./php/
            dockerfile: Dockerfilephp8
        image: php8-1:1.0
        networks:
            - lnmp-network
        volumes:
            - ../projects/:/var/www/:z

    database:
        image: mariadb:10.11.6
        environment:
            MARIADB_ROOT_PASSWORD: very-secret
            MARIADB_USER: cms_user
            MARIADB_PASSWORD: cms_secret
            MARIADB_DATABASE: cms
        networks:
            - lnmp-network
        volumes:
            - ./mariadb/data:/var/lib/mysql:z
            - ./mariadb/config/mariadb.cnf:/etc/mysql/mariadb.cnf

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 81:80
        networks:
            - lnmp-network
        environment:
            PMA_HOST: database

networks:
    lnmp-network:
