version: '3.8'
services:
    swagger:
        image: swaggerapi/swagger-editor
        ports:
        - 8081:8080
        environment:
        - SWAGGER_FILE=/tmp/openapi.yaml
        volumes:
        - ./openapi.yaml:/tmp:z
        restart: unless-stopped