version: '3'

services:
  nodejs:
    image: node:20.10.0-slim
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    working_dir: /app
    volumes:
      - ../../frontend:/app:z